package com.example.vinyylilista;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.example.vinyylilista.domain.Artist;
import com.example.vinyylilista.domain.ArtistRepository;
import com.example.vinyylilista.domain.User;
import com.example.vinyylilista.domain.UserRepository;
import com.example.vinyylilista.domain.Vinyl;
import com.example.vinyylilista.domain.VinylRepository;

@SpringBootApplication
public class VinyylilistaApplication {
	private static final Logger log = LoggerFactory.getLogger(VinyylilistaApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(VinyylilistaApplication.class, args);
	}
	
	@Bean
	public CommandLineRunner demo(VinylRepository vinylRepository, ArtistRepository artistRepository, UserRepository userRepository) {
		return (args) -> {
			log.info("save artists");
			Artist aerosmith = new Artist("Aerosmith");
			Artist aliceCooper = new Artist("Alice Cooper");
			Artist theArcs = new Artist("The Arcs");
			Artist badReligion = new Artist("Bad Religion");
			Artist beastieBoys = new Artist("Beastie Boys");
			Artist theBeatles = new Artist("The Beatles");
			Artist bigStar = new Artist("Big Star");
			Artist theBlackKeys = new Artist("The Black Keys");
			Artist blackSabbath = new Artist("Black Sabbath");
			Artist theClash = new Artist("The Clash");
			Artist ccr = new Artist("Creedence Clearwater Revival");
			Artist daftPunk = new Artist("Daft Punk");
			Artist danAuerbach = new Artist("Dan Auerbach");
			Artist davidBowie = new Artist("David Bowie");
			Artist deepPurple = new Artist("Deep Purple");
			Artist theDoors = new Artist("The Doors");
			Artist dxxxaDNukkehallitus = new Artist("Dxxxa D & Nukkehallitus");
			Artist entombed = new Artist("Entombed");
			Artist hurriganes = new Artist("Hurriganes");
			Artist imperialStateElectric = new Artist("Imperial State Electric");
			Artist jimiHendrix = new Artist("Jimi Hendrix");
			Artist jimiHendrixExperience = new Artist("The Jimi Hendrix Experience");
			Artist johnLennon = new Artist("John Lennon");
			Artist kaleidobolt = new Artist("Kaleidobolt");
			Artist kingCrimson = new Artist("King Crimson");
			Artist kingGizzard = new Artist("King Gizzard And The Lizard Wizard");
			Artist theKinks = new Artist("The Kinks");
			Artist ledZeppelin = new Artist("Led Zeppelin");
			Artist maNumminen = new Artist("M.A. Numminen");
			Artist nikkiLane = new Artist("Nikki Lane");
			Artist theOffspring = new Artist("The Offspring");
			Artist papaRoach = new Artist("Papa Roach");
			Artist paulMcCartney = new Artist("Paul McCartney");
			Artist pinkFloyd = new Artist("Pink Floyd");
			Artist prodigy = new Artist("Prodigy");
			Artist ramones = new Artist("Ramones");
			Artist serjTankian = new Artist("Serj Tankian");
			Artist stam1na = new Artist("Stam1na");
			Artist steveMillerBand = new Artist("Steve Miller Band");
			Artist suomenTalvisota = new Artist("Suomen Talvisota 1939-1940");
			Artist superjointRitual = new Artist("Superjoint Ritual");
			Artist tRex = new Artist("T. Rex");
			Artist tomJones = new Artist("Tom Jones");
			Artist tortureKiller = new Artist("Torture Killer");
			Artist theZombies = new Artist("The Zombies");
			
			artistRepository.save(aerosmith);
			artistRepository.save(aliceCooper);
			artistRepository.save(theArcs);
			artistRepository.save(badReligion);
			artistRepository.save(beastieBoys);
			artistRepository.save(theBeatles);
			artistRepository.save(bigStar);
			artistRepository.save(theBlackKeys);
			artistRepository.save(blackSabbath);
			artistRepository.save(theClash);
			artistRepository.save(ccr);
			artistRepository.save(daftPunk);
			artistRepository.save(danAuerbach);
			artistRepository.save(davidBowie);
			artistRepository.save(deepPurple);
			artistRepository.save(theDoors);
			artistRepository.save(dxxxaDNukkehallitus);
			artistRepository.save(entombed);
			artistRepository.save(hurriganes);
			artistRepository.save(imperialStateElectric);
			artistRepository.save(jimiHendrix);
			artistRepository.save(jimiHendrixExperience);
			artistRepository.save(johnLennon);
			artistRepository.save(kaleidobolt);
			artistRepository.save(kingCrimson);
			artistRepository.save(kingGizzard);
			artistRepository.save(theKinks);
			artistRepository.save(ledZeppelin);
			artistRepository.save(maNumminen);
			artistRepository.save(nikkiLane);
			artistRepository.save(theOffspring);
			artistRepository.save(papaRoach);
			artistRepository.save(paulMcCartney);
			artistRepository.save(pinkFloyd);
			artistRepository.save(prodigy);
			artistRepository.save(ramones);
			artistRepository.save(serjTankian);
			artistRepository.save(stam1na);
			artistRepository.save(steveMillerBand);
			artistRepository.save(suomenTalvisota);
			artistRepository.save(superjointRitual);
			artistRepository.save(tRex);
			artistRepository.save(tomJones);
			artistRepository.save(tortureKiller);
			artistRepository.save(theZombies);
			
			log.info("save records");
			Vinyl rocks = new Vinyl("Rocks", aerosmith, 1976, "Rock", "12-inch", "-");
			Vinyl killer = new Vinyl("Killer", aliceCooper, 1971, "Rock", "12-inch", "-");
			Vinyl theBreadcrumbs = new Vinyl("The Breadcrumbs", aliceCooper, 2019, "Rock", "10-inch", "Numbered limited edition");
			Vinyl yoursDreamily = new Vinyl("Yours, Dreamily,", theArcs, 2015, "Rock", "12-inch", "-");
			Vinyl ageOfUnreason = new Vinyl("Age Of Unreason", badReligion, 2019, "Punk", "12-inch", "-");
			Vinyl licensedToIll = new Vinyl("Licensed to Ill", beastieBoys, 1986, "Hip hop", "12-inch", "-");
			Vinyl abbeyRoad = new Vinyl("Abbey Road", theBeatles, 1969, "Rock", "12-inch", "-");
			Vinyl letItBe = new Vinyl("Let It Be", theBeatles, 1970, "Rock", "12-inch", "-");
			Vinyl revolver = new Vinyl("Revolver", theBeatles, 1966, "Rock", "12-inch", "Mono mix");
			Vinyl rubberSoul = new Vinyl("Rubber Soul", theBeatles, 1965, "Rock", "12-inch", "Mono mix");
			Vinyl theSinglesCollection = new Vinyl("The Singles Collection", theBeatles, 2019, "Rock", "Box set", "23 x 7-inch");
			Vinyl radioCity = new Vinyl("Radio City", bigStar, 1974, "Rock", "12-inch", "Mono mix");
			Vinyl brothers = new Vinyl("Brothers", theBlackKeys, 2010, "Rock", "12-inch", "2 x LP");
			Vinyl letsRock = new Vinyl("Let's Rock", theBlackKeys, 2019, "Rock", "12-inch", "-");
			Vinyl thevinylcollection = new Vinyl("The Vinyl Collection 1970 - 1978", blackSabbath, 2019, "Rock", "Box set", "9 x 12-inch + 7-inch");
			Vinyl londonCalling = new Vinyl("London Calling", theClash, 1979, "Punk", "12-inch", "-");
			Vinyl cosmosFactory = new Vinyl("Cosmo's Factory", ccr, 1970, "Rock", "12-inch", "-");
			Vinyl greenRiver = new Vinyl("Green River", ccr, 1969, "Rock", "12-inch", "-");
			Vinyl alive1997 = new Vinyl("Alive 1997", daftPunk, 2001, "Electronic", "12-inch", "-");
			Vinyl waitingOnASong = new Vinyl("Waiting On A Song", danAuerbach, 2017, "Rock", "12-inch", "-");
			Vinyl aladdinSane = new Vinyl("Aladdin Sane", davidBowie, 1973, "Rock", "12-inch", "-");
			Vinyl ziggyStardust = new Vinyl("The Rise And Fall Of Ziggy Stardust And The Spiders From Mars", davidBowie, 1972, "Rock", "12-inch", "-");
			Vinyl burn = new Vinyl("Burn", deepPurple, 1974, "Rock", "12-inch", "-");
			Vinyl inRock = new Vinyl("Deep Purple In Rock", deepPurple, 1970, "Rock", "12-inch", "-");
			Vinyl fireball = new Vinyl("Fireball", deepPurple, 1971, "Rock", "12-inch", "-");
			Vinyl absolutelyLive = new Vinyl("Absolutely Live", theDoors, 1970, "Psychedelic Rock", "12-inch", "2 x LP");
			Vinyl strangeDays = new Vinyl("Strange Days", theDoors, 1967, "Psychedelic Rock", "12-inch", "Mono mix");
			Vinyl theDoorsSelfTitled = new Vinyl("The Doors", theDoors, 1967, "Psychedelic Rock", "12-inch", "Mono mix");
			Vinyl maaan = new Vinyl("Määän", dxxxaDNukkehallitus, 2017, "Avant-garde", "12-inch", "Craziest shit I've got");
			Vinyl wolverineBlues = new Vinyl("Wolverine Blues", entombed, 1993, "Death Metal", "12-inch", "-");
			Vinyl crazyDays = new Vinyl("Crazy Days", hurriganes, 1975, "Rock", "12-inch", "-");
			Vinyl allThroughTheNight = new Vinyl("All Through The Night", imperialStateElectric, 2016, "Rock", "12-inch", "Limited edition");
			Vinyl honkMachine = new Vinyl("Honk Machine", imperialStateElectric, 2015, "Rock", "12-inch", "-");
			Vinyl imperialStateElectricSt = new Vinyl("Imperial State Electric", imperialStateElectric, 2010, "Rock", "12-inch", "-");
			Vinyl popWar = new Vinyl("Pop War", imperialStateElectric, 2012, "Rock", "12-inch", "-");
			Vinyl machineGun = new Vinyl("Machine Gun: The Fillmore East First Show 12/31/1969", jimiHendrix, 2016, "Psychedelic Rock", "12-inch", "2 x LP");
			Vinyl areYouExperienced = new Vinyl("Are You Experienced", jimiHendrixExperience, 1967, "Psychedelic Rock", "12-inch", "2 x LP Reissue");
			Vinyl axisBoldAsLove = new Vinyl("Axis: Bold As Love", jimiHendrixExperience, 1967, "Psychedelic Rock", "12-inch", "-");
			Vinyl electricLadyland = new Vinyl("Electric Ladyland", jimiHendrixExperience, 1968, "Psychedelic Rock", "12-inch", "2 x LP");
			Vinyl lennon = new Vinyl("Lennon", johnLennon, 2015, "Rock", "Box Set", "8 x LP");
			Vinyl bitter = new Vinyl("Bitter", kaleidobolt, 2019, "Prog Rock", "12-inch", "Signed by the band");
			Vinyl inTheCourt = new Vinyl("In The Court Of The Crimson King", kingCrimson, 1969, "Prog Rock", "12-inch", "-");
			Vinyl kG = new Vinyl("K.G. (Explorations Into Microtonal Tuning Volume 2)", kingGizzard, 2021, "Psychedelic Rock", "12-inch", "-");
			Vinyl murderOfTheUniverse = new Vinyl("Murder Of The Universe", kingGizzard, 2017, "Garage Rock", "12-inch", "-");
			Vinyl arthur = new Vinyl("Arthur Or The Decline And Fall Of The British Empire", theKinks, 1969, "Rock", "12-inch", "Mono mix");
			Vinyl ledZeppelinSt = new Vinyl("Led Zeppelin", ledZeppelin, 1969, "Rock", "12-inch", "-");
			Vinyl ledZeppelin2 = new Vinyl("Led Zeppelin II", ledZeppelin, 1969, "Rock", "12-inch", "-");
			Vinyl ledZeppelin3 = new Vinyl("Led Zeppelin III", ledZeppelin, 1970, "Rock", "12-inch", "-");
			Vinyl ledZeppelin4 = new Vinyl("Led Zeppelin IV", ledZeppelin, 1971, "Rock", "12-inch", "-");
			Vinyl aarteeni = new Vinyl("Aarteeni, Juokaamme Likööri!", maNumminen, 1973, "Jazz", "12-inch", "-");
			Vinyl allOrNothin = new Vinyl("All Or Nothin'", nikkiLane, 2014, "Country", "12-inch", "Signed by the artist");
			Vinyl walkOfShame = new Vinyl("Walk Of Shame", nikkiLane, 2011, "Country", "12-inch", "-");
			Vinyl americana = new Vinyl("Americana", theOffspring, 1998, "Punk", "12-inch", "-");
			Vinyl infest = new Vinyl("Infest", papaRoach, 2000, "Nu Metal", "12-inch", "-");
			Vinyl ram = new Vinyl("Ram", paulMcCartney, 1971, "Rock", "12-inch", "-");
			Vinyl animals = new Vinyl("Animals", pinkFloyd, 1977, "Prog Rock", "12-inch", "-");
			Vinyl atomHeartMother = new Vinyl("Atom Heart Mother", pinkFloyd, 1970, "Prog Rock", "12-inch", "-");
			Vinyl theDarkSideOfTheMoon = new Vinyl("The Dark Side Of The Moon", pinkFloyd, 1973, "Prog Rock", "12-inch", "-");
			Vinyl wishYouWereHere = new Vinyl("Wish You Were Here", pinkFloyd, 1975, "Prog Rock", "12-inch", "-");
			Vinyl theFatOfTheLand = new Vinyl("The Fat Of The Land", prodigy, 1997, "Electronic", "12-inch", "2 x LP");
			Vinyl leaveHome = new Vinyl("Leave Home", ramones, 1977, "Punk", "12-inch", "-");
			Vinyl rocketToRussia = new Vinyl("Rocket To Russia", ramones, 1977, "Punk", "12-inch", "-");
			Vinyl harakiri = new Vinyl("Harakiri", serjTankian, 2019, "Metal", "12-inch", "Signed by the artist");
			Vinyl novusOrdoMundi = new Vinyl("Novus Ordo Mundi", stam1na, 2021, "Metal", "12-inch", "Limited edition");
			Vinyl flyLikeAnEagle = new Vinyl("Fly Like An Eagle", steveMillerBand, 1976, "Rock", "12-inch", "-");
			Vinyl undergroundRock = new Vinyl("Underground-Rock", suomenTalvisota, 1970, "Rock", "12-inch", "-");
			Vinyl lethalDoseOfAmericanHatred = new Vinyl("A Lethal Dose Of American Hatred", superjointRitual, 2003, "Hardcore", "12-inch", "-");
			Vinyl useOnceAndDestroy = new Vinyl("Use Once And Destroy", superjointRitual, 2002, "Hardcore", "12-inch", "-");
			Vinyl electricWarrior = new Vinyl("Electric Warrior", tRex, 1971, "Rock", "12-inch", "-");
			Vinyl hotLove = new Vinyl("Hot Love", tRex, 1971, "Rock", "7-inch", "-");
			Vinyl tanx = new Vinyl("Tanx", tRex, 1971, "Rock", "12-inch", "-");
			Vinyl theSlider = new Vinyl("The Slider", tRex, 1972, "Rock", "12-inch", "-");
			Vinyl iWhoHaveNothing = new Vinyl("I (Who Have Nothing)", tomJones, 1970, "Pop", "7-inch", "-");
			Vinyl shesALadyMyWay = new Vinyl("She's A Lady / My Way", tomJones, 1971, "Pop", "7-inch", "-");
			Vinyl swarm = new Vinyl("Swarm!", tortureKiller, 2006, "Death Metal", "12-inch", "-");
			Vinyl beginHere = new Vinyl("Begin Here", theZombies, 1965, "Rock", "12-inch", "Mono mix");
			Vinyl odesseyAndOracle = new Vinyl("Odessey And Oracle", theZombies, 1968, "Rock", "12-inch", "Mono mix signed by Rod & Colin");
		
			vinylRepository.save(rocks);
			vinylRepository.save(killer);
			vinylRepository.save(theBreadcrumbs);
			vinylRepository.save(yoursDreamily);
			vinylRepository.save(ageOfUnreason);
			vinylRepository.save(licensedToIll);
			vinylRepository.save(abbeyRoad);
			vinylRepository.save(letItBe);
			vinylRepository.save(revolver);
			vinylRepository.save(rubberSoul);
			vinylRepository.save(theSinglesCollection);
			vinylRepository.save(radioCity);
			vinylRepository.save(brothers);
			vinylRepository.save(letsRock);
			vinylRepository.save(thevinylcollection);
			vinylRepository.save(londonCalling);
			vinylRepository.save(cosmosFactory);
			vinylRepository.save(greenRiver);
			vinylRepository.save(alive1997);
			vinylRepository.save(waitingOnASong);
			vinylRepository.save(aladdinSane);
			vinylRepository.save(ziggyStardust);
			vinylRepository.save(burn);
			vinylRepository.save(inRock);
			vinylRepository.save(fireball);
			vinylRepository.save(absolutelyLive);
			vinylRepository.save(strangeDays);
			vinylRepository.save(theDoorsSelfTitled);
			vinylRepository.save(maaan);
			vinylRepository.save(wolverineBlues);
			vinylRepository.save(crazyDays);
			vinylRepository.save(allThroughTheNight);
			vinylRepository.save(honkMachine);
			vinylRepository.save(imperialStateElectricSt);
			vinylRepository.save(popWar);
			vinylRepository.save(machineGun);
			vinylRepository.save(areYouExperienced);
			vinylRepository.save(axisBoldAsLove);
			vinylRepository.save(electricLadyland);
			vinylRepository.save(lennon);
			vinylRepository.save(bitter);
			vinylRepository.save(inTheCourt);
			vinylRepository.save(kG);
			vinylRepository.save(murderOfTheUniverse);
			vinylRepository.save(arthur);
			vinylRepository.save(ledZeppelinSt);
			vinylRepository.save(ledZeppelin2);
			vinylRepository.save(ledZeppelin3);
			vinylRepository.save(ledZeppelin4);
			vinylRepository.save(aarteeni);
			vinylRepository.save(allOrNothin);
			vinylRepository.save(walkOfShame);
			vinylRepository.save(americana);
			vinylRepository.save(infest);
			vinylRepository.save(ram);
			vinylRepository.save(animals);
			vinylRepository.save(atomHeartMother);
			vinylRepository.save(theDarkSideOfTheMoon);
			vinylRepository.save(wishYouWereHere);
			vinylRepository.save(theFatOfTheLand);
			vinylRepository.save(leaveHome);
			vinylRepository.save(rocketToRussia);
			vinylRepository.save(harakiri);
			vinylRepository.save(novusOrdoMundi);
			vinylRepository.save(flyLikeAnEagle);
			vinylRepository.save(undergroundRock);
			vinylRepository.save(lethalDoseOfAmericanHatred);
			vinylRepository.save(useOnceAndDestroy);
			vinylRepository.save(electricWarrior);
			vinylRepository.save(hotLove);
			vinylRepository.save(tanx);
			vinylRepository.save(theSlider);
			vinylRepository.save(iWhoHaveNothing);
			vinylRepository.save(shesALadyMyWay);
			vinylRepository.save(swarm);
			vinylRepository.save(beginHere);
			vinylRepository.save(odesseyAndOracle);
		
			User user = new User("admin", "$2a$10$XBS.2lf8thYKQbdombpI6u1bwgAyoAGMyLFij8jC1.vzofJ7Ccxli", "ADMIN");
		
			userRepository.save(user);
		
		
		
		log.info("fetch all vinyls");
		for (Vinyl vinyl : vinylRepository.findAll()) {
			log.info(vinyl.toString());
		}
		
		};
	}
}

